export const GET_SENDED_SUCCESS = 'GET_SENDED_SUCCESS';

export const GET_TARGETED_SUCCESS = 'GET_TARGETED_SUCCESS';

export const GET_OFFER_INFO_SUCCESS = 'GET_OFFER_INFO_SUCCESS';

export const OFFER_CREATE_PENDING = 'OFFER_CREATE_PENDING';
export const OFFER_CREATE_CANCELED = 'OFFER_CREATE_CANCELED';
export const OFFER_CREATE_SUCCESS = 'OFFER_CREATE_SUCCESS';

export const OFFER_ACCEPT_SUCCESS = 'OFFER_ACCEPT_SUCCESS';

export const OFFER_REJECT_SUCCESS = 'OFFER_REJECT_SUCCESS';

export const OFFER_CANCEL_SUCCESS = 'OFFER_CANCEL_SUCCESS';

export const OFFER_CREATE_SET_TARGET = 'OFFER_CREATE_SET_TARGET';
export const OFFER_CREATE_SET_SELECTED = 'OFFER_CREATE_SET_SELECTED';

export const OFFER_CLEAR_ERROR = 'OFFER_CLEAR_ERROR';
export const OFFER_ERROR = 'OFFER_ERROR';