export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_ERROR = 'GET_CATEGORY_LIST_ERROR';
export const ITEM_ADD_SUCCESS = 'ITEM_ADD_SUCCESS';
export const ITEM_ADD_ERROR = 'ITEM_ADD_ERROR';
export const ITEM_ON_TRADE_LIST_SUCCESS = 'ITEM_ON_TRADE_LIST_SUCCESS';
export const ITEM_ON_TRADE_LIST_ERROR = 'ITEM_ON_TRADE_LIST_ERROR';