export const ITEM_ADD_SUCCESS = 'ITEM_ADD_SUCCESS';
export const GET_USER_ITEMS_SUCCESS = 'GET_USER_ITEMS_SUCCESS';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const ITEM_ON_TRADE_LIST_SUCCESS = 'ITEM_ON_TRADE_LIST_SUCCESS';
export const ITEM_STATUS_SWITCH_SUCCESS = 'ITEM_STATUS_SWITCH_SUCCESS';

export const ITEM_CLEAR_ERROR = 'ITEM_CLEAR_ERROR';
export const ITEM_ERROR = 'ITEM_ERROR';
