export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const STATUS_SWITCH_SUCCESS = 'STATUS_SWITCH_SUCCESS';
export const STATUS_SWITCH_ERROR = 'STATUS_SWITCH_ERROR';