export const GET_SENDED_SUCCESS = 'GET_SENDED_SUCCESS';
export const GET_SENDED_ERROR = 'GET_SENDED_ERROR';
export const GET_TARGETED_SUCCESS = 'GET_TARGETED_SUCCESS';
export const GET_TARGETED_ERROR = 'GET_TARGETED_ERROR';

export const OFFER_CREATE_PENDING = 'OFFER_CREATE_PENDING';
export const OFFER_CREATE_CANCELED = 'OFFER_CREATE_CANCELED';
export const OFFER_CREATE_SUCCESS = 'OFFER_CREATE_SUCCESS';
export const OFFER_CREATE_ERROR = 'OFFER_CREATE_ERROR';
export const OFFER_ACCEPT_SUCCESS = 'OFFER_ACCEPT_SUCCESS';
export const OFFER_ACCEPT_ERROR = 'OFFER_ACCEPT_ERROR';
export const OFFER_REJECT_SUCCESS = 'OFFER_REJECT_SUCCESS';
export const OFFER_REJECT_ERROR = 'OFFER_REJECT_ERROR';
export const OFFER_CANCEL_SUCCESS = 'OFFER_CANCEL_SUCCESS';
export const OFFER_CANCEL_ERROR = 'OFFER_CANCEL_ERROR';
//TODO: use .reduce to change selected offer status